# Generated by Django 5.0.3 on 2024-03-09 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('kod', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Xomashyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Omborxona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qolgan_miqdori', models.FloatField()),
                ('narx', models.FloatField()),
                ('xomashyo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.xomashyo')),
            ],
        ),
        migrations.CreateModel(
            name='MahsulotXomashyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdori', models.FloatField()),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.mahsulot')),
                ('xomashyo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.xomashyo')),
            ],
        ),
    ]
